include $(srctree)/drivers/misc/mediatek/Makefile.custom

ifeq ($(CONFIG_ARCH_MT6572), y)
  obj-$(CONFIG_MTK_SENSOR_SUPPORT) += mt6572/ 
endif
ifeq ($(CONFIG_ARCH_MT6582), y)
  obj-$(CONFIG_MTK_SENSOR_SUPPORT) += mt6582/
endif

