#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y				+= kd_flashlightlist.o
obj-y				+= main_strobe2.o
obj-y				+= strobe_part_id.o
obj-y				+= sub_strobe2.o
obj-y				+= sub_strobe.o