include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y   +=  hx8379a_dsi_vdo_azet_ips.o
obj-y   +=  ili9806c_dsi_vdo_txd.o
obj-y   +=  ili9806c_dsi_vdo_azet_ips.o
obj-y   +=  ili9806c_dsi_vdo_djn.o
obj-y   +=  otm8018b_dsi_vdo_trust.o
obj-y   +=  ili9806c_dsi_vdo_txd_ips.o

