include $(srctree)/drivers/misc/mediatek/Makefile.custom


obj-y   +=  alsps.o

ifeq ($(CONFIG_MTK_GP2AP002S00F),y)
obj-y	+=  gp2ap002s00f/
endif

ifeq ($(CONFIG_MTK_CM36283),y)
obj-y	+=  cm36283/
endif
ifeq ($(CONFIG_MTK_TMD2771),y)
obj-y	+=  tmd2771/
endif
