#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-y += sensordriver/sensordrive_lens.o
obj-$(CONFIG_MTK_LENS_DUMMYLENS_SUPPORT) += dummy_lens/
obj-$(CONFIG_MTK_LENS_DW9714AF_SUPPORT) += dw9714af/
obj-$(CONFIG_MTK_LENS_FM50AF_SUPPORT) += fm50af/
obj-$(CONFIG_MTK_LENS_GAF001AF_SUPPORT)  += gaf001af/
obj-$(CONFIG_MTK_LENS_GAF002AF_SUPPORT)  += gaf002af/
obj-$(CONFIG_MTK_LENS_GAF008AF_SUPPORT)  += gaf008af/