#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-y += sensordriver/sensordrive_lens.o

obj-$(CONFIG_MTK_LENS_DUMMYLENS_SUPPORT) += dummy_lens/
obj-$(CONFIG_MTK_LENS_AD5823AF_SUPPORT) += ad5823af/
obj-$(CONFIG_MTK_LENS_BU6424AF_SUPPORT) += bu6424af/
obj-$(CONFIG_MTK_LENS_BU6429AF_SUPPORT) += bu6429af/
obj-$(CONFIG_MTK_LENS_DW9718AF_SUPPORT) += dw9718af/
obj-$(CONFIG_MTK_LENS_FM50AF_SUPPORT) += fm50af/
obj-$(CONFIG_MTK_LENS_MT9P017AF_SUPPORT) += mt9p017af/
obj-$(CONFIG_MTK_LENS_OV8825AF_SUPPORT) += ov8825af/



