# MTK Platform Support
obj-$(CONFIG_MT_SND_SOC_V1) += AudDrv_Afe.o AudDrv_Ana.o AudDrv_Clk.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_afe_control.o mt_soc_afe_connection.o mt_soc_pcm_common.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_capture.o mt_soc_pcm_dl1.o mt_soc_pcm_dummy.o mt_soc_pcm_routing.o mt_soc_pcm_capture2.o 
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_voice.o mt_soc_pcm_voice_bt.o mt_soc_pcm_voice_bt.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_hdmi.o mt_soc_pcm_dl1_i2s0.o mt_soc_pcm_dl1_i2s0Dl1.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_uldlloopback.o 
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_mrgrx.o mt_soc_pcm_mrgrx_awb.o 
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_dl1_awb.o mt_soc_pcm_dl1_bt.o mt_soc_pcm_bt_dai.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_dai_stub.o mt_soc_dai_routing.o mt_soc_codec_dummy.o mt_soc_codec_63xx.o mt_soc_pcm_fmtx.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_machine.o
obj-$(CONFIG_MTK_SPEAKER) += mt_soc_codec_speaker_63xx.o