include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)

obj-y += sched/
obj-$(CONFIG_MTK_MEMCFG) += mtk_memcfg.o
obj-y += mtk_meminfo.o
obj-y += system.o
obj-y += mt_cache_v7.o
obj-y += fiq_smp_call.o
obj-y += sec_osal.o
