#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-y				+= kd_sensorlist.o
obj-$(CONFIG_MTK_SENSOR_SUPPORT) := kd_sensorlist.o
