include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y   +=  hx8357c_hvga_dsi_cmd.o
obj-y   +=  hx8379a_dsi_vdo_azet_ips.o
obj-y   +=  hx8389b_qhd_dsi_vdo_tianma.o
obj-y   +=  ili9486_hvga_dsi_cmd.o
obj-y   +=  ili9806c_dsi_vdo_azet_ips.o
obj-y   +=  nt35512_wvga_dsi_vdo_boe.o
obj-y   +=  nt35517_qhd_dsi_vdo.o
obj-y   +=  otm8018b_dsi_vdo_boe_g6.o
obj-y   +=  nt35590_dsi_cmd_6571_fwvga.o
